# Generated by Django 5.0.1 on 2024-02-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_internal_code_and_more'),
    ]

    operations = [
    ]
