# Generated by Django 5.0.1 on 2024-02-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
