# Generated by Django 5.0.1 on 2024-02-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_supplierproduct_product_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(through='products.SupplierProduct', to='suppliers.suppliers'),
        ),
    ]
