# Generated by Django 5.0.1 on 2024-02-11 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_minimum_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productinventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='inventory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.inventory'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productinventory',
            unique_together={('product', 'inventory')},
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='local',
        ),
    ]
