# Generated by Django 5.0.1 on 2024-02-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_inventory_alter_productinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productinventory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='inventory',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
