# Generated by Django 5.0.1 on 2024-02-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
    ]
