# Generated by Django 5.0.1 on 2024-02-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_inventory_productinventory_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock',
        ),
    ]
