# Generated by Django 5.0.1 on 2024-02-11 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_minimum_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock',
        ),
    ]
