# Generated by Django 5.0.1 on 2024-02-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_minimum_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=255),
        ),
    ]
