# Generated by Django 5.0.1 on 2024-02-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_minimum_stock'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='products',
            field=models.ManyToManyField(through='products.ProductInventory', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, through='products.SupplierProduct', to='suppliers.suppliers'),
        ),
    ]
