# Generated by Django 5.0.1 on 2024-02-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_inventory_products_product_suppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.ManyToManyField(blank=True, through='products.ProductInventory', to='products.inventory'),
        ),
    ]
