from django.db import models
from sales_order.models import SalesOrder

class Invoice(models.Model):
    sale_order = models.ForeignKey(SalesOrder, on_delete=models.DO_NOTHING)
    access_key = models.CharField(max_length=255)
    barcode = models.CharField(max_length=255)
    emitter_name = models.CharField(max_length=255)
    emitter_fantasy_name = models.CharField(max_length=255)
    emitter_state_registration = models.CharField(max_length=255)
    emitter_cnpj = models.CharField(max_length=20)
    emitter_email = models.EmailField(max_length=255)
    emitter_zipcode = models.CharField(max_length=20)
    emitter_street = models.CharField(max_length=255)
    emitter_number = models.CharField(max_length=255)
    emitter_city = models.CharField(max_length=255)
    emitter_state = models.CharField(max_length=255)
    emitter_phone = models.CharField(max_length=255)
    receiver_name = models.CharField(max_length=255)
    receiver_fantasy_name = models.CharField(max_length=255)
    receiver_cnpj = models.CharField(max_length=20)
    receiver_email = models.EmailField(max_length=255)
    receiver_zipcode = models.CharField(max_length=20)
    receiver_street = models.CharField(max_length=255)
    receiver_number = models.CharField(max_length=255)
    receiver_city = models.CharField(max_length=255)
    receiver_state = models.CharField(max_length=255)
    receiver_phone = models.CharField(max_length=255)
    emission_date = models.DateTimeField(auto_now_add=True)
    