# Generated by Django 5.0.2 on 2024-02-25 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active_alter_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
    ]
