# Generated by Django 5.0.2 on 2024-02-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_employee_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
