# Generated by Django 5.0.1 on 2024-02-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('sales_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sale_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales_order.salesorder'),
        ),
    ]
