# Generated by Django 5.0.1 on 2024-02-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_access_key_invoice_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='access_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='barcode',
            field=models.CharField(max_length=255),
        ),
    ]
