# Generated by Django 5.0.1 on 2024-02-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_receiver_city_invoice_receiver_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='emitter_fantasy_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='emitter_state_registration',
            field=models.CharField(max_length=255),
        ),
    ]
