# Generated by Django 5.0.1 on 2024-02-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=255),
        ),
    ]
