# Generated by Django 5.0.1 on 2024-02-19 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_inventory_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
