# Generated by Django 5.0.1 on 2024-02-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=255),
        ),
    ]
