# Generated by Django 5.0.2 on 2024-02-27 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasesproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='purchasesproduct',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchases'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='products',
            field=models.ManyToManyField(through='purchases.PurchasesProduct', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasesproduct',
            unique_together={('product', 'purchase')},
        ),
    ]
