# Generated by Django 5.0.2 on 2024-02-20 22:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='suppliers',
            new_name='supplier',
        ),
        migrations.AddField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasesproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01, message='Informe um valor válido')]),
        ),
        migrations.AlterField(
            model_name='purchasesproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AlterField(
            model_name='purchasesproduct',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Informe um valor válido')]),
        ),
        migrations.AlterField(
            model_name='purchasesproduct',
            name='unit_value',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01, message='Informe um valor válido')]),
        ),
    ]
