# Generated by Django 5.0.2 on 2024-02-20 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_rename_suppliers_purchases_supplier_purchases_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='user',
        ),
    ]
