# Generated by Django 5.0.2 on 2024-02-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
