# Generated by Django 5.0.1 on 2024-02-18 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
