# Generated by Django 5.0.1 on 2024-02-18 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sales_order', '0002_alter_salesorderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clients'),
        ),
    ]
