# Generated by Django 5.0.1 on 2024-02-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0002_alter_salesorder_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderproduct',
            old_name='total_value',
            new_name='total_value_product',
        ),
    ]
