# Generated by Django 5.0.1 on 2024-02-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0004_alter_salesorderproduct_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesorderproduct',
            unique_together=set(),
        ),
    ]
